apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: thanos-receiver
  labels:
    operators.coreos.com/grafana-operator.thanos-receiver: ''
spec:
  name: grafana-operator
  channel: alpha
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: grafana-operator.v3.10.1
  installPlanGeneration: 1
  installPlanApproval: Automatic
