apiVersion: v1
kind: Secret
metadata:
  name: store-credentials
  namespace: thanos-receiver
stringData:
  store-secret.yaml: |
    type: AZURE
    config:
      storage_account: "thanosreceiver"
      storage_account_key: "DHinkeDcaCgn/xnQYruVjqH7kxmE3nokV4U4WhuJ1u+1qjaB998J5a25tGifmB7BV9vqIAiXUN6kDpLp29lb/g=="
      container: "thanosmetrics"
      max_retries: 0