name: Lint
on:
  pull_request:
    paths:
    - '**.md'
jobs:
  lint:
      runs-on: ubuntu-latest
      steps:
        - name: Check out code
          uses: actions/checkout@v2
        - uses: nosborn/github-action-markdown-cli@v2.0.0
          with:
            files: .
