name: Spellcheck Action
on: push
continue-on-error: true
jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.14.0
      name: Spellcheck
      with:
        config_path: .github/config/.spellcheck.yml
        task_name: Markdown
